export const GET_MY_FAMILIES = 'GET_MY_FAMILIES';
export const GET_MEMBERS_BY_FAMILY = 'GET_MEMBERS_BY_FAMILY';
export const GET_BALANCES_BY_FAMILY = 'GET_BALANCES_BY_FAMILY';
export const GET_NO_BALANCEDS_BY_FAMILY = 'GET_NO_BALANCEDS_BY_FAMILY';

export const EDIT_MEMBERS = 'EDIT_MEMBERS';
export const EDIT_ADMINS = 'EDIT_ADMINS';
export const EDIT_CREATOR = 'EDIT_CREATOR';

export const GET_MY_LOANS = 'GET_MY_LOANS';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
